name: Destroy config
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        id: init
        run: terraform -chdir=terraform/ init
      - name: Terraform destroy
        id: destroy
        run: terraform -chdir=terraform/ destroy -auto-approve -input=false
